In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from pandas import read_excel
from pandas import read_csv
import math
import seaborn as sns
from pylab import rcParams

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
%matplotlib inline

#Reading The Patients Data

In [3]:
# load the dataset

dataframe = read_csv('/content/patients.csv')
dataframe

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,NaN,999-65-3251,NaN,NaN,NaN,Damon455,Langosh790,NaN,...,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9.039165e+03,7964.1255
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,S99941126,NaN,NaN,Thi53,Wunsch504,NaN,...,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,4.027234e+05,14064.1350
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi716,Greenfelder433,NaN,...,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,5.719359e+05,787.5375
3,d488232e-bf14-4bed-08c0-a82f34b6a197,2003-01-28,NaN,999-56-6057,S99929424,NaN,Ms.,Phillis443,Walter473,NaN,...,Boston Massachusetts US,677 Ritchie Terrace,Hingham,Massachusetts,Plymouth County,2043.0,42.200491,-70.916076,5.825578e+05,104782.2070
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,1993-12-23,NaN,999-91-4320,S99991143,X44132498X,Mr.,Jerrold404,Herzog843,NaN,...,Boston Massachusetts US,276 Bernier Branch,Revere,Massachusetts,Suffolk County,NaN,42.381875,-70.999286,4.758269e+05,18067.0950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,409330fa-7ffd-dbfb-4eba-2349d58a6324,1979-02-28,NaN,999-68-5445,S99991649,X72884711X,Mr.,Coy949,Schaden604,NaN,...,Fitchburg Massachusetts US,434 Hickle Throughway Suite 15,Amherst,Massachusetts,Hampshire County,NaN,42.380084,-72.527376,1.050937e+06,346.5075
1159,cb328021-a854-dc94-e7ae-426580477308,1964-05-31,NaN,999-10-6445,S99986790,X86596484X,Mrs.,Sherry479,Barrows492,NaN,...,Boston Massachusetts US,976 Ortiz Orchard,Stoughton,Massachusetts,Norfolk County,NaN,42.081223,-71.126028,8.031471e+05,553335.4420
1160,41862157-5c14-f706-4a94-d2929be969e7,1967-07-12,NaN,999-63-2407,S99976335,X68999803X,Mr.,Vance413,Jakubowski832,NaN,...,Brockton Massachusetts US,534 Strosin Corner,Gardner,Massachusetts,Worcester County,1440.0,42.604215,-72.013243,1.028321e+06,28607.5050
1161,d53c57a5-4480-2481-32ee-b2844a991c9d,1948-07-28,NaN,999-37-8036,S99939062,X79037907X,Mr.,Cody889,Hilll811,NaN,...,Stoneham Massachusetts US,568 Ryan Stravenue,Mashpee,Massachusetts,Barnstable County,NaN,41.577704,-70.507460,2.638801e+05,155042.0520
1162,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,S99963285,X2822177X,Mr.,Haywood675,Schroeder447,NaN,...,Peabody Massachusetts US,707 Heathcote Wall Suite 15,Marblehead,Massachusetts,Essex County,NaN,42.466700,-70.903323,1.548721e+06,217.1100

In [4]:
dataframe=dataframe.rename(columns={"Id": "PATIENTID"})

In [5]:
dataframe.dtypes

PATIENTID               object
BIRTHDATE               object
DEATHDATE               object
SSN                     object
DRIVERS                 object
PASSPORT                object
PREFIX                  object
FIRST                   object
LAST                    object
SUFFIX                  object
MAIDEN                  object
MARITAL                 object
RACE                    object
ETHNICITY               object
GENDER                  object
BIRTHPLACE              object
ADDRESS                 object
CITY                    object
STATE                   object
COUNTY                  object
ZIP                    float64
LAT                    float64
LON                    float64
HEALTHCARE_EXPENSES    float64
HEALTHCARE_COVERAGE    float64
dtype: object

In [6]:
# load the dataset

dataframe1 = read_csv('/content/conditions.csv')
dataframe1

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
0,2013-06-24,2013-07-02,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,0b2794bd-ec2b-d34f-0610-2523b3b7fcf0,10509002,Acute bronchitis (disorder)
1,2016-02-27,2016-03-14,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,a6d818dd-0983-fd1c-eefa-3d2295532c45,283371005,Laceration of forearm
2,2016-08-11,2016-08-22,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,36d2e781-4655-0a11-1f70-c69856e02019,444814009,Viral sinusitis (disorder)
3,2016-11-27,2016-12-17,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,c8eaaf41-958b-31ab-7de5-568cee8751f3,444814009,Viral sinusitis (disorder)
4,2017-02-22,2017-06-02,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,16114001,Fracture of ankle
...,...,...,...,...,...,...
38089,2020-01-10,2021-01-15,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,090096d3-9404-3cb5-d1eb-583bf4c39180,160903007,Full-time employment (finding)
38090,2020-12-27,2021-01-03,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,db101ad8-66e2-9feb-e0cf-b2618f873c3a,38822007,Cystitis
38091,2021-01-15,NaN,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,160904001,Part-time employment (finding)
38092,2021-01-15,NaN,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,73595000,Stress (finding)
38093,2021-01-15,NaN,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,706893006,Victim of intimate partner abuse (finding)

In [7]:
dataframe1=dataframe1.rename(columns={"PATIENT": "PATIENTID"})

In [8]:
dataframe1.dtypes

START          object
STOP           object
PATIENTID      object
ENCOUNTER      object
CODE            int64
DESCRIPTION    object
dtype: object

#Clean The Data by Dropping Unwanted CLoumns / Rows

Data cleaning
Drop irrelevant columns

In [9]:
dataframe = dataframe.drop(['DRIVERS', 'SUFFIX'], axis=1)

In [10]:
# Remove duplicate records
dataframe = dataframe.drop_duplicates()

#Merge datasets based on common columns (Integrate Records)

In [11]:
df = pd.merge(dataframe, dataframe1, on='PATIENTID', how='inner')

In [12]:
df

,PATIENTID,BIRTHDATE,DEATHDATE,SSN,PASSPORT,PREFIX,FIRST,LAST,MAIDEN,MARITAL,...,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,START,STOP,ENCOUNTER,CODE,DESCRIPTION
0,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,NaN,NaN,Thi53,Wunsch504,NaN,NaN,...,NaN,42.035213,-71.482519,402723.415,14064.135,2013-06-24,2013-07-02,0b2794bd-ec2b-d34f-0610-2523b3b7fcf0,10509002,Acute bronchitis (disorder)
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,NaN,NaN,Thi53,Wunsch504,NaN,NaN,...,NaN,42.035213,-71.482519,402723.415,14064.135,2016-02-27,2016-03-14,a6d818dd-0983-fd1c-eefa-3d2295532c45,283371005,Laceration of forearm
2,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,NaN,NaN,Thi53,Wunsch504,NaN,NaN,...,NaN,42.035213,-71.482519,402723.415,14064.135,2016-08-11,2016-08-22,36d2e781-4655-0a11-1f70-c69856e02019,444814009,Viral sinusitis (disorder)
3,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,NaN,NaN,Thi53,Wunsch504,NaN,NaN,...,NaN,42.035213,-71.482519,402723.415,14064.135,2016-11-27,2016-12-17,c8eaaf41-958b-31ab-7de5-568cee8751f3,444814009,Viral sinusitis (disorder)
4,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,NaN,NaN,Thi53,Wunsch504,NaN,NaN,...,NaN,42.035213,-71.482519,402723.415,14064.135,2017-02-22,2017-06-02,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,16114001,Fracture of ankle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38089,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,X2822177X,Mr.,Haywood675,Schroeder447,NaN,M,...,NaN,42.466700,-70.903323,1548720.970,217.110,2020-01-10,2021-01-15,090096d3-9404-3cb5-d1eb-583bf4c39180,160903007,Full-time employment (finding)
38090,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,X2822177X,Mr.,Haywood675,Schroeder447,NaN,M,...,NaN,42.466700,-70.903323,1548720.970,217.110,2020-12-27,2021-01-03,db101ad8-66e2-9feb-e0cf-b2618f873c3a,38822007,Cystitis
38091,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,X2822177X,Mr.,Haywood675,Schroeder447,NaN,M,...,NaN,42.466700,-70.903323,1548720.970,217.110,2021-01-15,NaN,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,160904001,Part-time employment (finding)
38092,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,X2822177X,Mr.,Haywood675,Schroeder447,NaN,M,...,NaN,42.466700,-70.903323,1548720.970,217.110,2021-01-15,NaN,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,73595000,Stress (finding)
38093,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,X2822177X,Mr.,Haywood675,Schroeder447,NaN,M,...,NaN,42.466700,-70.903323,1548720.970,217.110,2021-01-15,NaN,1516d2e6-4846-5f1e-fe27-c1ebb9a39f72,706893006,Victim of intimate partner abuse (finding)

In [13]:
df.dtypes

PATIENTID               object
BIRTHDATE               object
DEATHDATE               object
SSN                     object
PASSPORT                object
PREFIX                  object
FIRST                   object
LAST                    object
MAIDEN                  object
MARITAL                 object
RACE                    object
ETHNICITY               object
GENDER                  object
BIRTHPLACE              object
ADDRESS                 object
CITY                    object
STATE                   object
COUNTY                  object
ZIP                    float64
LAT                    float64
LON                    float64
HEALTHCARE_EXPENSES    float64
HEALTHCARE_COVERAGE    float64
START                   object
STOP                    object
ENCOUNTER               object
CODE                     int64
DESCRIPTION             object
dtype: object

# Data transformation
Apply transformations to columns

In [14]:
# Convert date columns to datetime format
df['START'] = pd.to_datetime(df['START'])
df['STOP'] = pd.to_datetime(df['STOP'])

In [15]:
df.dtypes

PATIENTID                      object
BIRTHDATE                      object
DEATHDATE                      object
SSN                            object
PASSPORT                       object
PREFIX                         object
FIRST                          object
LAST                           object
MAIDEN                         object
MARITAL                        object
RACE                           object
ETHNICITY                      object
GENDER                         object
BIRTHPLACE                     object
ADDRESS                        object
CITY                           object
STATE                          object
COUNTY                         object
ZIP                           float64
LAT                           float64
LON                           float64
HEALTHCARE_EXPENSES           float64
HEALTHCARE_COVERAGE           float64
START                  datetime64[ns]
STOP                   datetime64[ns]
ENCOUNTER                      object
CODE                            int64
DESCRIPTION                    object
dtype: object

#### Calculate length of HEALTHCARE_COVERAGE

In [16]:
df['HEALTHCARE_COVERAGE_LENGTH'] = (df['STOP'] - df['START']).dt.days

### Apply data transformations to categorical variables

In [17]:
df['GENDER'] = df['GENDER'].map({'M': 'Male', 'F': 'Female'})

## Save the cleaned, integrated, and transformed dataset

In [19]:
# Save the cleaned, integrated, and transformed dataset
df.to_csv('/content/cleaned_records.csv', index=False)

In [20]:
df.describe()

,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,START,STOP,CODE,HEALTHCARE_COVERAGE_LENGTH
count,20605.000000,38094.000000,38094.000000,3.809400e+04,3.809400e+04,38094,29925,3.809400e+04,29925.000000
mean,1996.638534,42.245420,-71.354238,2.041481e+06,4.007928e+05,2001-12-21 16:24:00.226807296,2004-05-01 20:59:04.060150272,4.927406e+13,584.985664
min,1001.000000,41.299942,-73.445165,5.147439e+03,0.000000e+00,1919-06-06 00:00:00,1922-08-31 00:00:00,1.734006e+06,0.000000
25%,1830.000000,42.089248,-71.535785,1.115480e+06,1.198805e+04,1991-09-22 12:00:00,1995-03-08 00:00:00,8.475701e+07,84.000000
50%,2116.000000,42.295183,-71.145240,1.799452e+06,1.338132e+05,2009-06-20 12:00:00,2012-04-09 00:00:00,1.609030e+08,371.000000
75%,2190.000000,42.462164,-71.011924,2.286987e+06,3.765214e+05,2016-07-12 00:00:00,2017-08-13 00:00:00,2.242990e+08,406.000000
max,2861.000000,42.888532,-69.978831,2.311655e+07,1.356228e+07,2021-11-15 00:00:00,2021-11-18 00:00:00,1.093988e+16,20195.000000
std,452.698853,0.294193,0.641146,2.619780e+06,1.335352e+06,NaN,NaN,7.292378e+14,1111.793865